name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pr:
- main
- release/*

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish vscode-proxy-agent
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: vscode-proxy-agent

        buildSteps:
          - script: npm ci
            displayName: Install dependencies
          - script: npm run compile
            displayName: Compile

        testPlatforms:
          - name: Linux
            nodeVersions:
              - 20.x

        testSteps:
          - script: npm ci
            displayName: Install dependencies
          - script: npm run compile
            displayName: Compile
          - script: docker run --rm -v `pwd`/..:/repo -w /repo/tests/test-client node:20 npm i
            workingDirectory: tests
            displayName: Install test dependencies
          - script: docker ps -a -q | xargs docker rm -f && docker compose run test-direct-client
            workingDirectory: tests
            displayName: Test direct client
          - script: docker ps -a -q | xargs docker rm -f && docker compose run test-proxy-client
            workingDirectory: tests
            displayName: Test proxy client

        publishPackage: ${{ parameters.publishPackage }}